### ISSUE TITLE
Login: Simple Frontend

### ISSUE THREAD

**Issue by raihanizar** [raihanizar/eventmakers-algorithmic#11]

**Comment by raihanizar** [comment]
sebagai referensi aja kalau bingung, bisa diikuti atau tidak 

- utk task **simple frontend** minimal bisa tampil data di halaman dulu, 
- gak harus fetch data pakai kode, bisa pakai data dummy, diambil manual dari GET di https://eventmakers-api.fly.dev/documentation
- referensi lihat di halaman `events/page.js`

**Comment by BrezyBaihaqi** [comment]
oke mas @raihanizar
