### ISSUE TITLE
Login: Backend

### ISSUE THREAD

**Issue by BrezyBaihaqi** [raihanizar/eventmakers-algorithmic#17]

**Comment by BrezyBaihaqi** [comment]
mas @dilekilla saya coba kerjain yang login backend dulu ya. kalau mas @dilekilla mau kerjain login fe kabarin ya

**Comment by raihanizar** [comment]
@BrezyBaihaqi @dilekilla , nanti kalo dapet authentication response jangan lupa:
- `payload` masukin `localStorage`
- `token` masukin cookies

biar nanti kalo bikin backend buat autorisasi halaman event, enak tinggal ambil data"nya 👍 

referensi: 
- `payload`: [video pertemuan 17](https://www.youtube.com/watch?v=bInoqb4h-rE) 
- `token`: [video pertemuan 18](https://www.youtube.com/watch?v=6QozPDAzB80)

**Comment by BrezyBaihaqi** [comment]
mas @raihanizar saya mau push ga bisa alasannya 
`git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.`
